version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.2-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

